const INITIAL_EMPTY_STRING_VALUE = '';
const INITIAL_EMPTY_NUMBER_VALUE = 0;
const DEFAULT_MODAL_SIZE = '280px';

export { INITIAL_EMPTY_STRING_VALUE, INITIAL_EMPTY_NUMBER_VALUE, DEFAULT_MODAL_SIZE };
