const INITIAL_ID_BOARD_VALUE = '';
const MAX_TITLE_LENGTH = 16;
const MIN_TITLE_LENGTH = 3;
const MIN_WIDTH_MODAL = '300px';

export { INITIAL_ID_BOARD_VALUE, MAX_TITLE_LENGTH, MIN_TITLE_LENGTH, MIN_WIDTH_MODAL };
