const MIN_WIDTH_MODAL = '300px';
const INITIAL_INPUT_VALUE = '';
const MAX_TITLE_LENGTH = 12;
const MAX_DESCRIPTION_LENGTH = 24;
const MIN_INPUT_VALUE_LENGTH = 6;

export {
  MIN_WIDTH_MODAL,
  INITIAL_INPUT_VALUE,
  MAX_TITLE_LENGTH,
  MAX_DESCRIPTION_LENGTH,
  MIN_INPUT_VALUE_LENGTH,
};
